-- v0.1.26: справочник стран ISO 3166-1 alpha-2.
--
-- Используется для:
--   - <CountrySelect> в форме создания Remnawave-ноды (countryCode)
--   - В будущем: vps_servers.location, plans geo-targeting, AdminStats по странам
--
-- Поля:
--   code        — ISO 3166-1 alpha-2 (RU, US, ...) или 'XX' для «не указано»
--   name_ru     — русское название
--   name_en     — английское название (для англоязычного UI / поиска)
--   flag        — emoji флаг
--   region      — континент: EU, NA, SA, AS, AF, OC, AN, или NULL для XX
--   is_popular  — TRUE для топ-30 — выводится первыми в селекторе

CREATE TABLE IF NOT EXISTS countries (
  code        CHAR(2) PRIMARY KEY,
  name_ru     VARCHAR(128) NOT NULL,
  name_en     VARCHAR(128) NOT NULL,
  flag        VARCHAR(8),
  region      VARCHAR(8),
  is_popular  BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS idx_countries_popular ON countries(is_popular) WHERE is_popular = true;
CREATE INDEX IF NOT EXISTS idx_countries_region ON countries(region);

-- ─── Сидинг ──────────────────────────────────────────────────────────────────

-- "Не указано" — для нод без конкретной страны
INSERT INTO countries (code, name_ru, name_en, flag, region, is_popular) VALUES
('XX', 'Не указано', 'Unknown', '🌍', NULL, true)
ON CONFLICT (code) DO NOTHING;

-- Топ-30 popular (часто-встречающиеся VPS-локации)
INSERT INTO countries (code, name_ru, name_en, flag, region, is_popular) VALUES
('RU', 'Россия',          'Russia',         '🇷🇺', 'EU', true),
('UA', 'Украина',          'Ukraine',        '🇺🇦', 'EU', true),
('BY', 'Беларусь',         'Belarus',        '🇧🇾', 'EU', true),
('KZ', 'Казахстан',        'Kazakhstan',     '🇰🇿', 'AS', true),
('US', 'США',              'United States',  '🇺🇸', 'NA', true),
('GB', 'Великобритания',   'United Kingdom', '🇬🇧', 'EU', true),
('DE', 'Германия',         'Germany',        '🇩🇪', 'EU', true),
('NL', 'Нидерланды',       'Netherlands',    '🇳🇱', 'EU', true),
('FI', 'Финляндия',        'Finland',        '🇫🇮', 'EU', true),
('FR', 'Франция',          'France',         '🇫🇷', 'EU', true),
('IT', 'Италия',           'Italy',          '🇮🇹', 'EU', true),
('ES', 'Испания',          'Spain',          '🇪🇸', 'EU', true),
('PL', 'Польша',           'Poland',         '🇵🇱', 'EU', true),
('CH', 'Швейцария',        'Switzerland',    '🇨🇭', 'EU', true),
('AT', 'Австрия',          'Austria',        '🇦🇹', 'EU', true),
('SE', 'Швеция',           'Sweden',         '🇸🇪', 'EU', true),
('NO', 'Норвегия',         'Norway',         '🇳🇴', 'EU', true),
('DK', 'Дания',            'Denmark',        '🇩🇰', 'EU', true),
('CZ', 'Чехия',            'Czechia',        '🇨🇿', 'EU', true),
('TR', 'Турция',           'Turkey',         '🇹🇷', 'AS', true),
('AE', 'ОАЭ',              'UAE',            '🇦🇪', 'AS', true),
('JP', 'Япония',           'Japan',          '🇯🇵', 'AS', true),
('KR', 'Южная Корея',      'South Korea',    '🇰🇷', 'AS', true),
('SG', 'Сингапур',         'Singapore',      '🇸🇬', 'AS', true),
('HK', 'Гонконг',          'Hong Kong',      '🇭🇰', 'AS', true),
('CA', 'Канада',           'Canada',         '🇨🇦', 'NA', true),
('AU', 'Австралия',         'Australia',      '🇦🇺', 'OC', true),
('BR', 'Бразилия',         'Brazil',         '🇧🇷', 'SA', true),
('IN', 'Индия',            'India',          '🇮🇳', 'AS', true),
('IL', 'Израиль',          'Israel',         '🇮🇱', 'AS', true)
ON CONFLICT (code) DO NOTHING;

-- Остальные страны — алфавит по name_en. Полный список ISO 3166-1 alpha-2.
INSERT INTO countries (code, name_ru, name_en, flag, region) VALUES
('AF', 'Афганистан',           'Afghanistan',                    '🇦🇫', 'AS'),
('AL', 'Албания',              'Albania',                        '🇦🇱', 'EU'),
('DZ', 'Алжир',                'Algeria',                        '🇩🇿', 'AF'),
('AS', 'Американское Самоа',   'American Samoa',                 '🇦🇸', 'OC'),
('AD', 'Андорра',              'Andorra',                        '🇦🇩', 'EU'),
('AO', 'Ангола',               'Angola',                         '🇦🇴', 'AF'),
('AI', 'Ангилья',              'Anguilla',                       '🇦🇮', 'NA'),
('AQ', 'Антарктида',           'Antarctica',                     '🇦🇶', 'AN'),
('AG', 'Антигуа и Барбуда',    'Antigua and Barbuda',            '🇦🇬', 'NA'),
('AR', 'Аргентина',            'Argentina',                      '🇦🇷', 'SA'),
('AM', 'Армения',              'Armenia',                        '🇦🇲', 'AS'),
('AW', 'Аруба',                'Aruba',                          '🇦🇼', 'NA'),
('AZ', 'Азербайджан',          'Azerbaijan',                     '🇦🇿', 'AS'),
('BS', 'Багамы',               'Bahamas',                        '🇧🇸', 'NA'),
('BH', 'Бахрейн',              'Bahrain',                        '🇧🇭', 'AS'),
('BD', 'Бангладеш',            'Bangladesh',                     '🇧🇩', 'AS'),
('BB', 'Барбадос',             'Barbados',                       '🇧🇧', 'NA'),
('BE', 'Бельгия',              'Belgium',                        '🇧🇪', 'EU'),
('BZ', 'Белиз',                'Belize',                         '🇧🇿', 'NA'),
('BJ', 'Бенин',                'Benin',                          '🇧🇯', 'AF'),
('BM', 'Бермуды',              'Bermuda',                        '🇧🇲', 'NA'),
('BT', 'Бутан',                'Bhutan',                         '🇧🇹', 'AS'),
('BO', 'Боливия',              'Bolivia',                        '🇧🇴', 'SA'),
('BA', 'Босния и Герцеговина', 'Bosnia and Herzegovina',         '🇧🇦', 'EU'),
('BW', 'Ботсвана',             'Botswana',                       '🇧🇼', 'AF'),
('BV', 'Остров Буве',          'Bouvet Island',                  '🇧🇻', 'AN'),
('IO', 'БИОТ',                 'British Indian Ocean Territory', '🇮🇴', 'AS'),
('BN', 'Бруней',               'Brunei',                         '🇧🇳', 'AS'),
('BG', 'Болгария',             'Bulgaria',                       '🇧🇬', 'EU'),
('BF', 'Буркина-Фасо',         'Burkina Faso',                   '🇧🇫', 'AF'),
('BI', 'Бурунди',              'Burundi',                        '🇧🇮', 'AF'),
('CV', 'Кабо-Верде',           'Cabo Verde',                     '🇨🇻', 'AF'),
('KH', 'Камбоджа',             'Cambodia',                       '🇰🇭', 'AS'),
('CM', 'Камерун',              'Cameroon',                       '🇨🇲', 'AF'),
('KY', 'Острова Кайман',       'Cayman Islands',                 '🇰🇾', 'NA'),
('CF', 'ЦАР',                  'Central African Republic',       '🇨🇫', 'AF'),
('TD', 'Чад',                  'Chad',                           '🇹🇩', 'AF'),
('CL', 'Чили',                 'Chile',                          '🇨🇱', 'SA'),
('CN', 'Китай',                'China',                          '🇨🇳', 'AS'),
('CX', 'Остров Рождества',     'Christmas Island',               '🇨🇽', 'OC'),
('CC', 'Кокосовые острова',    'Cocos Islands',                  '🇨🇨', 'OC'),
('CO', 'Колумбия',             'Colombia',                       '🇨🇴', 'SA'),
('KM', 'Коморы',               'Comoros',                        '🇰🇲', 'AF'),
('CG', 'Конго',                'Congo',                          '🇨🇬', 'AF'),
('CD', 'ДР Конго',             'DR Congo',                       '🇨🇩', 'AF'),
('CK', 'Острова Кука',         'Cook Islands',                   '🇨🇰', 'OC'),
('CR', 'Коста-Рика',           'Costa Rica',                     '🇨🇷', 'NA'),
('CI', 'Кот-д''Ивуар',         'Cote d''Ivoire',                 '🇨🇮', 'AF'),
('HR', 'Хорватия',             'Croatia',                        '🇭🇷', 'EU'),
('CU', 'Куба',                 'Cuba',                           '🇨🇺', 'NA'),
('CW', 'Кюрасао',              'Curacao',                        '🇨🇼', 'NA'),
('CY', 'Кипр',                 'Cyprus',                         '🇨🇾', 'EU'),
('DJ', 'Джибути',              'Djibouti',                       '🇩🇯', 'AF'),
('DM', 'Доминика',             'Dominica',                       '🇩🇲', 'NA'),
('DO', 'Доминикана',           'Dominican Republic',             '🇩🇴', 'NA'),
('EC', 'Эквадор',              'Ecuador',                        '🇪🇨', 'SA'),
('EG', 'Египет',               'Egypt',                          '🇪🇬', 'AF'),
('SV', 'Сальвадор',            'El Salvador',                    '🇸🇻', 'NA'),
('GQ', 'Экв. Гвинея',          'Equatorial Guinea',              '🇬🇶', 'AF'),
('ER', 'Эритрея',              'Eritrea',                        '🇪🇷', 'AF'),
('EE', 'Эстония',              'Estonia',                        '🇪🇪', 'EU'),
('SZ', 'Эсватини',             'Eswatini',                       '🇸🇿', 'AF'),
('ET', 'Эфиопия',              'Ethiopia',                       '🇪🇹', 'AF'),
('FK', 'Фолкленды',            'Falkland Islands',               '🇫🇰', 'SA'),
('FO', 'Фарерские острова',    'Faroe Islands',                  '🇫🇴', 'EU'),
('FJ', 'Фиджи',                'Fiji',                           '🇫🇯', 'OC'),
('GF', 'Французская Гвиана',   'French Guiana',                  '🇬🇫', 'SA'),
('PF', 'Французская Полинезия','French Polynesia',               '🇵🇫', 'OC'),
('TF', 'Фр. Южные тер.',       'French Southern Territories',    '🇹🇫', 'AN'),
('GA', 'Габон',                'Gabon',                          '🇬🇦', 'AF'),
('GM', 'Гамбия',               'Gambia',                         '🇬🇲', 'AF'),
('GE', 'Грузия',               'Georgia',                        '🇬🇪', 'AS'),
('GH', 'Гана',                 'Ghana',                          '🇬🇭', 'AF'),
('GI', 'Гибралтар',            'Gibraltar',                      '🇬🇮', 'EU'),
('GR', 'Греция',               'Greece',                         '🇬🇷', 'EU'),
('GL', 'Гренландия',           'Greenland',                      '🇬🇱', 'NA'),
('GD', 'Гренада',              'Grenada',                        '🇬🇩', 'NA'),
('GP', 'Гваделупа',            'Guadeloupe',                     '🇬🇵', 'NA'),
('GU', 'Гуам',                 'Guam',                           '🇬🇺', 'OC'),
('GT', 'Гватемала',            'Guatemala',                      '🇬🇹', 'NA'),
('GG', 'Гернси',               'Guernsey',                       '🇬🇬', 'EU'),
('GN', 'Гвинея',               'Guinea',                         '🇬🇳', 'AF'),
('GW', 'Гвинея-Бисау',         'Guinea-Bissau',                  '🇬🇼', 'AF'),
('GY', 'Гайана',               'Guyana',                         '🇬🇾', 'SA'),
('HT', 'Гаити',                'Haiti',                          '🇭🇹', 'NA'),
('HM', 'О-ва Херд и Макдональд','Heard and McDonald Islands',     '🇭🇲', 'AN'),
('VA', 'Ватикан',              'Holy See',                       '🇻🇦', 'EU'),
('HN', 'Гондурас',             'Honduras',                       '🇭🇳', 'NA'),
('HU', 'Венгрия',              'Hungary',                        '🇭🇺', 'EU'),
('IS', 'Исландия',             'Iceland',                        '🇮🇸', 'EU'),
('ID', 'Индонезия',            'Indonesia',                      '🇮🇩', 'AS'),
('IR', 'Иран',                 'Iran',                           '🇮🇷', 'AS'),
('IQ', 'Ирак',                 'Iraq',                           '🇮🇶', 'AS'),
('IE', 'Ирландия',             'Ireland',                        '🇮🇪', 'EU'),
('IM', 'Остров Мэн',           'Isle of Man',                    '🇮🇲', 'EU'),
('JM', 'Ямайка',               'Jamaica',                        '🇯🇲', 'NA'),
('JE', 'Джерси',               'Jersey',                         '🇯🇪', 'EU'),
('JO', 'Иордания',             'Jordan',                         '🇯🇴', 'AS'),
('KE', 'Кения',                'Kenya',                          '🇰🇪', 'AF'),
('KI', 'Кирибати',             'Kiribati',                       '🇰🇮', 'OC'),
('KP', 'Северная Корея',       'North Korea',                    '🇰🇵', 'AS'),
('KW', 'Кувейт',               'Kuwait',                         '🇰🇼', 'AS'),
('KG', 'Киргизия',             'Kyrgyzstan',                     '🇰🇬', 'AS'),
('LA', 'Лаос',                 'Laos',                           '🇱🇦', 'AS'),
('LV', 'Латвия',               'Latvia',                         '🇱🇻', 'EU'),
('LB', 'Ливан',                'Lebanon',                        '🇱🇧', 'AS'),
('LS', 'Лесото',               'Lesotho',                        '🇱🇸', 'AF'),
('LR', 'Либерия',              'Liberia',                        '🇱🇷', 'AF'),
('LY', 'Ливия',                'Libya',                          '🇱🇾', 'AF'),
('LI', 'Лихтенштейн',          'Liechtenstein',                  '🇱🇮', 'EU'),
('LT', 'Литва',                'Lithuania',                      '🇱🇹', 'EU'),
('LU', 'Люксембург',           'Luxembourg',                     '🇱🇺', 'EU'),
('MO', 'Макао',                'Macao',                          '🇲🇴', 'AS'),
('MG', 'Мадагаскар',           'Madagascar',                     '🇲🇬', 'AF'),
('MW', 'Малави',               'Malawi',                         '🇲🇼', 'AF'),
('MY', 'Малайзия',             'Malaysia',                       '🇲🇾', 'AS'),
('MV', 'Мальдивы',             'Maldives',                       '🇲🇻', 'AS'),
('ML', 'Мали',                 'Mali',                           '🇲🇱', 'AF'),
('MT', 'Мальта',               'Malta',                          '🇲🇹', 'EU'),
('MH', 'Маршалловы острова',   'Marshall Islands',               '🇲🇭', 'OC'),
('MQ', 'Мартиника',            'Martinique',                     '🇲🇶', 'NA'),
('MR', 'Мавритания',           'Mauritania',                     '🇲🇷', 'AF'),
('MU', 'Маврикий',             'Mauritius',                      '🇲🇺', 'AF'),
('YT', 'Майотта',              'Mayotte',                        '🇾🇹', 'AF'),
('MX', 'Мексика',              'Mexico',                         '🇲🇽', 'NA'),
('FM', 'Микронезия',           'Micronesia',                     '🇫🇲', 'OC'),
('MD', 'Молдова',              'Moldova',                        '🇲🇩', 'EU'),
('MC', 'Монако',               'Monaco',                         '🇲🇨', 'EU'),
('MN', 'Монголия',             'Mongolia',                       '🇲🇳', 'AS'),
('ME', 'Черногория',           'Montenegro',                     '🇲🇪', 'EU'),
('MS', 'Монтсеррат',           'Montserrat',                     '🇲🇸', 'NA'),
('MA', 'Марокко',              'Morocco',                        '🇲🇦', 'AF'),
('MZ', 'Мозамбик',             'Mozambique',                     '🇲🇿', 'AF'),
('MM', 'Мьянма',               'Myanmar',                        '🇲🇲', 'AS'),
('NA', 'Намибия',              'Namibia',                        '🇳🇦', 'AF'),
('NR', 'Науру',                'Nauru',                          '🇳🇷', 'OC'),
('NP', 'Непал',                'Nepal',                          '🇳🇵', 'AS'),
('NC', 'Новая Каледония',      'New Caledonia',                  '🇳🇨', 'OC'),
('NZ', 'Новая Зеландия',        'New Zealand',                    '🇳🇿', 'OC'),
('NI', 'Никарагуа',            'Nicaragua',                      '🇳🇮', 'NA'),
('NE', 'Нигер',                'Niger',                          '🇳🇪', 'AF'),
('NG', 'Нигерия',              'Nigeria',                        '🇳🇬', 'AF'),
('NU', 'Ниуэ',                 'Niue',                           '🇳🇺', 'OC'),
('NF', 'Норфолк',              'Norfolk Island',                 '🇳🇫', 'OC'),
('MK', 'Северная Македония',   'North Macedonia',                '🇲🇰', 'EU'),
('MP', 'Северные Марианские',  'Northern Mariana Islands',       '🇲🇵', 'OC'),
('OM', 'Оман',                 'Oman',                           '🇴🇲', 'AS'),
('PK', 'Пакистан',             'Pakistan',                       '🇵🇰', 'AS'),
('PW', 'Палау',                'Palau',                          '🇵🇼', 'OC'),
('PS', 'Палестина',            'Palestine',                      '🇵🇸', 'AS'),
('PA', 'Панама',               'Panama',                         '🇵🇦', 'NA'),
('PG', 'Папуа — Новая Гвинея', 'Papua New Guinea',               '🇵🇬', 'OC'),
('PY', 'Парагвай',             'Paraguay',                       '🇵🇾', 'SA'),
('PE', 'Перу',                 'Peru',                           '🇵🇪', 'SA'),
('PH', 'Филиппины',            'Philippines',                    '🇵🇭', 'AS'),
('PN', 'Питкэрн',              'Pitcairn',                       '🇵🇳', 'OC'),
('PT', 'Португалия',           'Portugal',                       '🇵🇹', 'EU'),
('PR', 'Пуэрто-Рико',          'Puerto Rico',                    '🇵🇷', 'NA'),
('QA', 'Катар',                'Qatar',                          '🇶🇦', 'AS'),
('RE', 'Реюньон',              'Reunion',                        '🇷🇪', 'AF'),
('RO', 'Румыния',              'Romania',                        '🇷🇴', 'EU'),
('RW', 'Руанда',               'Rwanda',                         '🇷🇼', 'AF'),
('BL', 'Сен-Бартелеми',        'Saint Barthelemy',               '🇧🇱', 'NA'),
('SH', 'Остров Святой Елены',  'Saint Helena',                   '🇸🇭', 'AF'),
('KN', 'Сент-Китс и Невис',    'Saint Kitts and Nevis',          '🇰🇳', 'NA'),
('LC', 'Сент-Люсия',           'Saint Lucia',                    '🇱🇨', 'NA'),
('MF', 'Сен-Мартен (фр.)',     'Saint Martin',                   '🇲🇫', 'NA'),
('PM', 'Сен-Пьер и Микелон',   'Saint Pierre and Miquelon',      '🇵🇲', 'NA'),
('VC', 'Сент-Винсент',         'Saint Vincent and Grenadines',   '🇻🇨', 'NA'),
('WS', 'Самоа',                'Samoa',                          '🇼🇸', 'OC'),
('SM', 'Сан-Марино',           'San Marino',                     '🇸🇲', 'EU'),
('ST', 'Сан-Томе и Принсипи',  'Sao Tome and Principe',          '🇸🇹', 'AF'),
('SA', 'Саудовская Аравия',    'Saudi Arabia',                   '🇸🇦', 'AS'),
('SN', 'Сенегал',              'Senegal',                        '🇸🇳', 'AF'),
('RS', 'Сербия',               'Serbia',                         '🇷🇸', 'EU'),
('SC', 'Сейшелы',              'Seychelles',                     '🇸🇨', 'AF'),
('SL', 'Сьерра-Леоне',         'Sierra Leone',                   '🇸🇱', 'AF'),
('SX', 'Синт-Мартен (нид.)',   'Sint Maarten',                   '🇸🇽', 'NA'),
('SK', 'Словакия',             'Slovakia',                       '🇸🇰', 'EU'),
('SI', 'Словения',             'Slovenia',                       '🇸🇮', 'EU'),
('SB', 'Соломоновы острова',   'Solomon Islands',                '🇸🇧', 'OC'),
('SO', 'Сомали',               'Somalia',                        '🇸🇴', 'AF'),
('ZA', 'ЮАР',                  'South Africa',                   '🇿🇦', 'AF'),
('GS', 'Юж. Георгия и Юж. С.', 'South Georgia and S. Sandwich',  '🇬🇸', 'AN'),
('SS', 'Южный Судан',          'South Sudan',                    '🇸🇸', 'AF'),
('LK', 'Шри-Ланка',            'Sri Lanka',                      '🇱🇰', 'AS'),
('SD', 'Судан',                'Sudan',                          '🇸🇩', 'AF'),
('SR', 'Суринам',              'Suriname',                       '🇸🇷', 'SA'),
('SJ', 'Шпицберген и Ян-Майен','Svalbard and Jan Mayen',         '🇸🇯', 'EU'),
('SY', 'Сирия',                'Syria',                          '🇸🇾', 'AS'),
('TW', 'Тайвань',              'Taiwan',                         '🇹🇼', 'AS'),
('TJ', 'Таджикистан',          'Tajikistan',                     '🇹🇯', 'AS'),
('TZ', 'Танзания',             'Tanzania',                       '🇹🇿', 'AF'),
('TH', 'Таиланд',              'Thailand',                       '🇹🇭', 'AS'),
('TL', 'Восточный Тимор',      'Timor-Leste',                    '🇹🇱', 'AS'),
('TG', 'Того',                 'Togo',                           '🇹🇬', 'AF'),
('TK', 'Токелау',              'Tokelau',                        '🇹🇰', 'OC'),
('TO', 'Тонга',                'Tonga',                          '🇹🇴', 'OC'),
('TT', 'Тринидад и Тобаго',    'Trinidad and Tobago',            '🇹🇹', 'NA'),
('TN', 'Тунис',                'Tunisia',                        '🇹🇳', 'AF'),
('TM', 'Туркменистан',         'Turkmenistan',                   '🇹🇲', 'AS'),
('TC', 'Тёркс и Кайкос',       'Turks and Caicos Islands',       '🇹🇨', 'NA'),
('TV', 'Тувалу',               'Tuvalu',                         '🇹🇻', 'OC'),
('UG', 'Уганда',                'Uganda',                         '🇺🇬', 'AF'),
('UY', 'Уругвай',              'Uruguay',                        '🇺🇾', 'SA'),
('UZ', 'Узбекистан',           'Uzbekistan',                     '🇺🇿', 'AS'),
('VU', 'Вануату',              'Vanuatu',                        '🇻🇺', 'OC'),
('VE', 'Венесуэла',            'Venezuela',                      '🇻🇪', 'SA'),
('VN', 'Вьетнам',              'Vietnam',                        '🇻🇳', 'AS'),
('VG', 'Виргинские (Брит.)',   'Virgin Islands (British)',       '🇻🇬', 'NA'),
('VI', 'Виргинские (США)',     'Virgin Islands (US)',            '🇻🇮', 'NA'),
('WF', 'Уоллис и Футуна',      'Wallis and Futuna',              '🇼🇫', 'OC'),
('EH', 'Западная Сахара',      'Western Sahara',                 '🇪🇭', 'AF'),
('YE', 'Йемен',                'Yemen',                          '🇾🇪', 'AS'),
('ZM', 'Замбия',               'Zambia',                         '🇿🇲', 'AF'),
('ZW', 'Зимбабве',             'Zimbabwe',                       '🇿🇼', 'AF')
ON CONFLICT (code) DO NOTHING;
